[2023-12-13T23:40:34.899+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2023-12-13T18:40:24.718875+00:00 [queued]>
[2023-12-13T23:40:34.948+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2023-12-13T18:40:24.718875+00:00 [queued]>
[2023-12-13T23:40:34.949+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-13T23:40:35.023+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): get_data> on 2023-12-13 18:40:24.718875+00:00
[2023-12-13T23:40:35.033+0500] {standard_task_runner.py:57} INFO - Started process 80810 to run task
[2023-12-13T23:40:35.050+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'manual__2023-12-13T18:40:24.718875+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpt3m77jgl']
[2023-12-13T23:40:35.053+0500] {standard_task_runner.py:85} INFO - Job 8: Subtask get_data
[2023-12-13T23:40:35.440+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.get_data manual__2023-12-13T18:40:24.718875+00:00 [running]> on host ml-vb
[2023-12-13T23:40:35.986+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-13T18:40:24.718875+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-13T18:40:24.718875+00:00'
[2023-12-13T23:40:35.989+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-13T23:40:35.990+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/ml/project/flow/scripts/get_data.py']
[2023-12-13T23:40:36.023+0500] {subprocess.py:86} INFO - Output:
[2023-12-13T23:40:39.860+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-13T23:40:39.861+0500] {subprocess.py:93} INFO -   File "/home/ml/project/flow/scripts/get_data.py", line 4, in <module>
[2023-12-13T23:40:39.861+0500] {subprocess.py:93} INFO -     from pyyoutube import Api
[2023-12-13T23:40:39.863+0500] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'pyyoutube'
[2023-12-13T23:40:40.038+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-13T23:40:40.201+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ml/project/flow/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-13T23:40:40.214+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=get_data, execution_date=20231213T184024, start_date=20231213T184034, end_date=20231213T184040
[2023-12-13T23:40:40.313+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 80810)
[2023-12-13T23:40:40.396+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-13T23:40:40.616+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
